/*
 * File: app/store/Recipes.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.store.Recipes', {
    extend: 'Ext.data.Store',
    alias: 'store.recipes',

    singleton: true,
    requires: [
        'BeerBuilder.model.Recipe'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            model: 'BeerBuilder.model.Recipe',
            storeId: 'Recipes',
            data: [
                {
                    id: 1,
                    name: '4C\'s IPA',
                    style: 'India Pale Ale',
                    type: 'extract',
                    instructions: '<ol><li>Heat 2 Gals to 165, then steep Vienna and Crystals for 30 mins.</li><li>Remove Grains and add DME and heat to a Boil.</li><li>5 mins after boil, begin adding Hops add intended intervals.</li><li>After 60 mins, turn off heat and cover, Prepare Ice Bath.</li><li>I like to have 2 gals of Ice Cold Water from my Freezer ready in the Fermenter, before I add the Wort.</li><li>Then I throw in some Ice, and a Freezer Pack (after being sanitized) and then fill the Fermenter up with more Ice Cold Water. (I havent invested in any cool toys like Wort Chillers).</li><li>Bring the temp down to reccommended Levels (Below 80) and pitch Yeast.</li><li>I didnt use a starter, but i am sure it wouldnt hurt. I have the luxury of a Converted Freezer Chest to store my Fermenter.</li><li>I Fermented at 58 to reduce any esters being produced. (I am going to try 65 next time to see if there is a difference).</li><li>I brewed this a couple of months ago and it came out Great.</li><li>I have a few Friends that love IPS\'s and asked me to take a shot at it and I got great reviews and will continue to Brew this year round to keep in stock</li></ol>',
                    description: '<p>I got the name from using 4 Hops that all start with the Letter C, very clever... This brew ended up Citrusy with a Clean Finish. Very Hoppy but doen\'t have a Bite to it. The color is a Golden Copper Haze, because I chose not to use any Finings like Irish Moss. The aroma is Citrusy, Grapefruity</p>'
                },
                {
                    id: 2,
                    name: 'Bobs IPA',
                    style: 'Bobs Pale Ale',
                    type: 'bob extract',
                    instructions: '<ol><li>Heat 2 Gals to 165, then steep Vienna and Crystals for 30 mins.</li><li>Remove Grains and add DME and heat to a Boil.</li><li>5 mins after boil, begin adding Hops add intended intervals.</li><li>After 60 mins, turn off heat and cover, Prepare Ice Bath.</li><li>I like to have 2 gals of Ice Cold Water from my Freezer ready in the Fermenter, before I add the Wort.</li><li>Then I throw in some Ice, and a Freezer Pack (after being sanitized) and then fill the Fermenter up with more Ice Cold Water. (I havent invested in any cool toys like Wort Chillers).</li><li>Bring the temp down to reccommended Levels (Below 80) and pitch Yeast.</li><li>I didnt use a starter, but i am sure it wouldnt hurt. I have the luxury of a Converted Freezer Chest to store my Fermenter.</li><li>I Fermented at 58 to reduce any esters being produced. (I am going to try 65 next time to see if there is a difference).</li><li>I brewed this a couple of months ago and it came out Great.</li><li>I have a few Friends that love IPS\'s and asked me to take a shot at it and I got great reviews and will continue to Brew this year round to keep in stock</li></ol>',
                    description: '<p>I got the name from using 4 Hops that all start with the Letter C, very clever... This brew ended up Citrusy with a Clean Finish. Very Hoppy but doen\'t have a Bite to it. The color is a Golden Copper Haze, because I chose not to use any Finings like Irish Moss. The aroma is Citrusy, Grapefruity</p>'
                }
            ],
            proxy: {
                type: 'localstorage',
                id: 'recipe_ls'
            }
        }, cfg)]);
    }
});