/*
 * File: app/store/Units.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.store.Units', {
    extend: 'Ext.data.Store',

    singleton: true,
    requires: [
        'BeerBuilder.model.Unit'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            model: 'BeerBuilder.model.Unit',
            storeId: 'Units',
            data: [
                {
                    id: 1,
                    abbr: 'lb',
                    name: 'Pound'
                },
                {
                    id: 2,
                    abbr: 'oz',
                    name: 'Ounce'
                },
                {
                    id: 3,
                    abbr: 'tsp',
                    name: 'Teaspon'
                },
                {
                    id: 4,
                    abbr: 'tbsp',
                    name: 'Tablespoon'
                },
                {
                    id: 5,
                    abbr: 'pt',
                    name: 'Pint'
                },
                {
                    id: 6,
                    abbr: 'qt',
                    name: 'Quart'
                },
                {
                    id: 7,
                    abbr: 'gal',
                    name: 'Gallon'
                },
                {
                    id: 8,
                    abbr: 'gr',
                    name: 'Grain'
                }
            ],
            proxy: {
                type: 'localstorage',
                id: 'unit_ls'
            }
        }, cfg)]);
    }
});