/*
 * File: app/view/IngredientGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.view.IngredientGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.ingredientgridpanel',

    resizable: true,
    title: 'Ingredients',
    store: 'Ingredients',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Ingredient',
                    flex: 1,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false,
                        size: 100
                    }
                },
                {
                    xtype: 'actioncolumn',
                    flex: 1,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                view.getStore().removeAt(rowIndex);
                            },
                            icon: 'resources/delete.gif',
                            tooltip: 'Delete Ingredient'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var i = Ext.create('BeerBuilder.model.Ingredient', {
                                    name: 'new'
                                });

                                ingredientgrid = this.up('ingredientgridpanel');
                                ingredientgrid.getStore().insert(0,i);
                                ingredientgrid.getPlugin('ingredientroweditor').startEdit();
                            },
                            text: 'Add Ingredient'
                        }
                    ]
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {
                    pluginId: 'ingredientroweditor'
                })
            ]
        });

        me.callParent(arguments);
    }

});