/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.maintabpanel',

    requires: [
        'BeerBuilder.view.ViewContainer',
        'BeerBuilder.view.UnitGridPanel',
        'BeerBuilder.view.IngredientGridPanel',
        'BeerBuilder.view.RecipeEditPanel'
    ],

    height: 800,
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'viewcontainer'
                },
                {
                    xtype: 'unitgridpanel'
                },
                {
                    xtype: 'ingredientgridpanel'
                },
                {
                    xtype: 'recipeeditpanel',
                    title: 'Edit Recipes'
                }
            ]
        });

        me.callParent(arguments);
    }

});