/*
 * File: app/view/RecipeEditPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.view.RecipeEditPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.recipeeditpanel',

    requires: [
        'BeerBuilder.view.RecipesGridPanel',
        'BeerBuilder.view.RecipeFormPanel',
        'BeerBuilder.view.RecipeIngredientsGrid'
    ],

    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'recipesgridpanel',
                    flex: 1
                },
                {
                    xtype: 'recipeformpanel',
                    flex: 2
                },
                {
                    xtype: 'recipeingredientsgrid',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});