/*
 * File: app/view/UnitGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.view.UnitGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.unitgridpanel',

    resizable: true,
    title: 'Units',
    store: 'Units',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var u = Ext.create('BeerBuilder.model.Unit', {
                                    name: 'new'
                                });
                                unitgrid = this.up('unitgridpanel');
                                unitgrid.getStore().insert(0,u);
                                scoregrid.getPlugin('unitroweditor').startEdit();
                            },
                            text: 'Add New Unit'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Unit Name',
                    flex: 1,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false,
                        size: 60
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'abbr',
                    text: 'Abbr',
                    flex: 1,
                    editor: {
                        xtype: 'textfield',
                        allowBlank: false
                    }
                },
                {
                    xtype: 'actioncolumn',
                    flex: 1,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                view.getStore().removeAt(rowIndex);
                            },
                            icon: 'resources/delete.gif',
                            tooltip: 'Delete Unit'
                        }
                    ]
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {
                    pluginId: 'unitroweditor'
                })
            ]
        });

        me.callParent(arguments);
    }

});