/*
 * File: app/view/recipe/View.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BeerBuilder.view.recipe.View', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.recipeview',

    cls: 'item-ct',
    itemId: 'recipeview',
    autoScroll: true,
    layout: {
        align: 'middle',
        pack: 'center',
        type: 'hbox'
    },
    bodyBorder: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'component',
                    border: false,
                    itemId: 'contentCt',
                    tpl: [
                        '<div class="name">Recipe Name: {name}</div>',
                        '<div>Type: {type}</div>',
                        '<div>Style: {style}</div>',
                        '<div>Description:</div>',
                        '<div class="description">{description}</div>',
                        '<div>Instructions:</div>',
                        '<div class="directions">{instructions}</div>'
                    ],
                    width: 500
                }
            ]
        });

        me.callParent(arguments);
    },

    bind: function(record) {
        this.child('#contentCt').update(record.data);
    }

});